baseURL = ""
languageCode = "en-us"
title = "博客"
theme = "m10c"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  primaryColor = "#ffffff"
  lightColor = "#a2a2a2"
  lightestColor = "#d3d3d3"
